### ISSUE TITLE
bug: The instance crashed while loading data

### ISSUE THREAD

**Issue by haitaoguan** [stoneatom/stonedb#462] opened 2022-09-01 12:08 UTC
### Describe the problem

Failed to run load data file when a CSV file is larger than 25 GB. An OOM error occurred based on the system log.

### Expected behavior

The command "load data" is successfully.

### How To Reproduce

select * from jrk_all
into outfile '/tmp/jrk_all.csv'
FIELDS TERMINATED BY ',' 
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n';

The csv file is larger than 25 GB.

load data infile '/tmp/jrk_all.csv' into table jrk_all
FIELDS TERMINATED BY ',' 
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n';

### Environment

# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04 LTS
Release:	22.04
Codename:	jammy

# /stonedb57/install/bin/mysqld --version
/stonedb57/install/bin/mysqld  Ver 5.7.36-StoneDB for Linux on x86_64 (build-)
build information as follow: 
	Repository address: git@github.com:stoneatom/stonedb.git:stonedb-5.7
	Branch name: stonedb-5.7
	Last commit ID: 05eb397
	Last commit time: Date:   Mon Aug 15 14:05:47 2022 +0800
	Build time: Date: 2022年 08月 15日 星期一 15:38:53 CST

# free -g
               total        used        free      shared  buff/cache   available
Mem:              31           0          30           0           0          30
Swap:              7           0           7

### Are you interested in submitting a PR to solve the problem?

- [x] Yes, I will!

**Comment by duanfuxiang0** [comment] 2022-09-09 04:06
First, we analyze the Tianmu memory management module (path: stonedb/storage/tianmu/mm). All objects that inherit from `TraceableObject` are managed through this module, including RCAttr, Pack, ReadBuffer, RCIndex and so on. The following types of memory pools are currently available: 
- **SystemHeap**, use malloc/free system call;
- **MysqlHeap**, use mysql my_mallocl/my_free function;
- **TCMHeap**, use tcmalloc library function;
- **HugeHeap**, also use tcmalloc function, but enable HugePage.

The default config is to use **TCMheap** as the main memory pool and **SystemHeap** as the secondary memory pool. When the main memory pool is empty, the secondary memory pool will be used。

The following system parameters are related to memory management and can be used to adjust the memory management policy.
- **tianmu_mm_releasepolicy**       // memory release policy，include fifo | lru | all | 2q (default)
- **tianmu_mm_policy**                   // memory request policy, include system | mysql | tcmalloc(default)
- **tianmu_servermainheapsize**   // main memory pool size, default is half of the physical memory size.
- **tianmu_mm_hardlimit**              // If the main memory pool is empty, memory request will failed, rather than using the secondary memory pool, this is recommended to be enabled.
- **tianmu_hugefiledir**                   // large page memory directory, "" means not enable.
- **tianmu_mm_largetempratio**     // cache ratio, default is 0
- **tianmu_cachefolder**                 // directory for cache

By adjusting **tianmu_mm_hardlimit**, memory OOM can be avoided, but LOAD DATA will fail. this will not really solve the problem.

**Comment by RingsC** [comment] 2022-09-09 07:31
> 

So what's the root cause?

**Comment by duanfuxiang0** [comment] 2022-09-09 22:53
Analysis of the mysqld by `valgrind --tool=massif` shows that most of the memory allocation for LOAD DATA SQL occurs on Pack::Pack() and Pack::LoadValues().
```
99.95% (5,129,652,941B) (heap allocation functions) malloc/new/new[], --alloc-fns, etc.
->65.37% (3,355,115,520B) 0x2F5A359: Tianmu::mm::SystemHeap::alloc(unsigned long) (sys_heap_policy.cpp:31)
| ->65.37% (3,355,115,520B) 0x2F46567: Tianmu::mm::MemoryHandling::alloc(unsigned long, Tianmu::mm::BLOCK_TYPE, Tianmu::mm::TraceableObject*, bool) (memory_handling_policy.cpp:211)
|   ->65.37% (3,355,115,520B) 0x2F5CC5C: Tianmu::mm::TraceableObject::alloc(unsigned long, Tianmu::mm::BLOCK_TYPE, bool) (traceable_object.cpp:55)
|   |  ->27.57% (1,415,053,312B) 0x31D2550: Tianmu::core::PackStr::PackStr() (pack_str.cpp:49)      // <- PackStr init
|   |  ->23.07% (1,184,038,912B) 0x31D3A59: Tianmu::core::PackStr::LoadValues() (pack_str.cpp:232)  // <- PackStr load values
|   |  ->07.85% (402,653,184B) 0x32A4949: Tianmu::core::PackInt::LoadValuesFixed() (pack_int.cpp:440)                    
|   |  ->06.89% (353,370,112B) 0x31D259E: Tianmu::core::PackStr::PackStr() (pack_str.cpp:50)
|   ...
...
```
Accordingly, we guess that the memory is growing because the Pack object is not released in time. By analyzing the code logic, we can know the data loading process of RCAttr:
 - first, Pack data will be written to the cache (Tianmu::core::DataCache);
 - and then Pack data will be synced to disk; 
 - when the data is synced to disk, the Pack data will be deleted from the cache when executing Commit (RCAttr::SaveVersion).

But when we execute Load Data SQL, we will execute Commit only when all the data is fully loaded, and all the Packs will stay in memory during this time; this is the root cause of OOM. So when Load Data, writing a Pack data in the cache, syncing it to disk, and then deleting the Pack cache immediately will solve this problem.

**Comment by RingsC** [comment] 2022-09-19 02:23
> Analysis of the mysqld by `valgrind --tool=massif` shows that most of the memory allocation for LOAD DATA SQL occurs on Pack::Pack() and Pack::LoadValues().
> 
> ```
> 99.95% (5,129,652,941B) (heap allocation functions) malloc/new/new[], --alloc-fns, etc.
> ->65.37% (3,355,115,520B) 0x2F5A359: Tianmu::mm::SystemHeap::alloc(unsigned long) (sys_heap_policy.cpp:31)
> | ->65.37% (3,355,115,520B) 0x2F46567: Tianmu::mm::MemoryHandling::alloc(unsigned long, Tianmu::mm::BLOCK_TYPE, Tianmu::mm::TraceableObject*, bool) (memory_handling_policy.cpp:211)
> |   ->65.37% (3,355,115,520B) 0x2F5CC5C: Tianmu::mm::TraceableObject::alloc(unsigned long, Tianmu::mm::BLOCK_TYPE, bool) (traceable_object.cpp:55)
> |   |  ->27.57% (1,415,053,312B) 0x31D2550: Tianmu::core::PackStr::PackStr() (pack_str.cpp:49)      // <- PackStr init
> |   |  ->23.07% (1,184,038,912B) 0x31D3A59: Tianmu::core::PackStr::LoadValues() (pack_str.cpp:232)  // <- PackStr load values
> |   |  ->07.85% (402,653,184B) 0x32A4949: Tianmu::core::PackInt::LoadValuesFixed() (pack_int.cpp:440)                    
> |   |  ->06.89% (353,370,112B) 0x31D259E: Tianmu::core::PackStr::PackStr() (pack_str.cpp:50)
> |   ...
> ...
> ```
> 
> Accordingly, we guess that the memory is growing because the Pack object is not released in time. By analyzing the code logic, we can know the data loading process of RCAttr:
> 
> * first, Pack data will be written to the cache (Tianmu::core::DataCache);
> * and then Pack data will be synced to disk;
> * when the data is synced to disk, the Pack data will be deleted from the cache when executing Commit (RCAttr::SaveVersion).
> 
> But when we execute Load Data SQL, we will execute Commit only when all the data is fully loaded, and all the Packs will stay in memory during this time; this is the root cause of OOM. So when Load Data, writing a Pack data in the cache, syncing it to 
                                                                                                                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~          
disk, and then deleting the Pack cache immediately will solve this problem.

This will deteriorate performance of loading data.

**Closed as completed** 2022-09-21 09:29 UTC
Labels: A-bug
