### ISSUE TITLE
bug: SELECT * FROM BUG_12595 WHERE a LIKE 'hakan\n%' ESCAPE '\n' or ESCAPE '',ERROR : Incorrect arguments to ESCAPE

### ISSUE THREAD

**Issue by shangyanwen** [stoneatom/stonedb#273] opened 2022-07-21 04:04 UTC
### Describe the problem

```
SET @@SQL_MODE='NO_BACKSLASH_ESCAPES';
SHOW LOCAL VARIABLES LIKE 'SQL_MODE';

CREATE TABLE BUG_12595(a varchar(100))engine=stonedb;
INSERT INTO BUG_12595 VALUES ('hakan%'), ('hakank'), ("ha%an");

SELECT * FROM BUG_12595 WHERE a LIKE 'hakan\%' ESCAPE '\\';
SELECT * FROM BUG_12595 WHERE a LIKE 'hakan%' ESCAPE '';
SELECT * FROM BUG_12595 WHERE a LIKE 'hakan\n%' ESCAPE '\n';
##The above three  select errors are as follows
ERROR 1210 (HY000): Incorrect arguments to ESCAPE
```

### Expected behavior

```
##The following is：innodb test result

（1）SELECT * FROM BUG_12595 WHERE a LIKE 'hakan\%' ESCAPE '\\';
+--------+
| a      |
+--------+
| hakan% |
+--------+
1 row in set (0.00 sec)
（2）SELECT * FROM BUG_12595 WHERE a LIKE 'hakan%' ESCAPE '';
+--------+
| a      |
+--------+
| hakan% |
| hakank |
+--------+
2 rows in set (0.00 sec)
（3）SELECT * FROM BUG_12595 WHERE a LIKE 'hakan\n%' ESCAPE '\n';
+--------+
| a      |
+--------+
| hakan% |
+--------+
1 row in set (0.00 sec)
```

### How To Reproduce

```
SET @@SQL_MODE='NO_BACKSLASH_ESCAPES';
SHOW LOCAL VARIABLES LIKE 'SQL_MODE';

CREATE TABLE BUG_12595(a varchar(100))engine=stonedb;
INSERT INTO BUG_12595 VALUES ('hakan%'), ('hakank'), ("ha%an");

SELECT * FROM BUG_12595 WHERE a LIKE 'hakan\%' ESCAPE '\\';
SELECT * FROM BUG_12595 WHERE a LIKE 'hakan%' ESCAPE '';
SELECT * FROM BUG_12595 WHERE a LIKE 'hakan\n%' ESCAPE '\n';
```

### Environment

1. StoneDB for mysql5.7 (release)
2. Ubuntu 20.04.4

### Are you interested in submitting a PR to solve the problem?

- [ ] Yes, I will!

**Comment by adofsauron** [comment] 2022-11-24 01:41
ACK

**Comment by adofsauron** [comment] 2022-11-24 09:09
the same as https://github.com/stoneatom/stonedb/issues/271

**Comment by adofsauron** [comment] 2022-11-24 10:27
![lALPGT5jGNeKfl7NB1XNDas_3499_1877](https://user-images.githubusercontent.com/3915817/203760804-63198341-0345-4db1-8c0c-8f02777b9845.png)

```c++

(gdb) bt
#0  Item_func_like::eval_escape_clause (this=0x7f6df0005948, thd=0x7f6df0000e10) at /root/work/stonedb-dev-20221123/sql/item_cmpfunc.cc:6615
#1  0x0000000001d93a66 in Item_func_like::fix_fields (this=0x7f6df0005948, thd=0x7f6df0000e10, ref=0x7f6df0004c58) at /root/work/stonedb-dev-20221123/sql/item_cmpfunc.cc:6533
#2  0x00000000023eebe6 in st_select_lex::setup_conds (this=0x7f6df0004b80, thd=0x7f6df0000e10) at /root/work/stonedb-dev-20221123/sql/sql_resolver.cc:1191
#3  0x00000000023ec263 in st_select_lex::prepare (this=0x7f6df0004b80, thd=0x7f6df0000e10) at /root/work/stonedb-dev-20221123/sql/sql_resolver.cc:212
#4  0x0000000002c6a776 in Tianmu::core::optimize_select (thd=0x7f6df0000e10, select_options=2147748608, result=0x7f6df00063f8, select_lex=0x7f6df0004b80, optimize_after_tianmu=@0x7f6fe968fdcc: 0, 
    free_join=@0x7f6fe968fdd0: 1) at /root/work/stonedb-dev-20221123/storage/tianmu/core/engine_execute.cpp:336
#5  0x0000000002c6a130 in Tianmu::core::Engine::HandleSelect (this=0x50607a0, thd=0x7f6df0000e10, lex=0x7f6df0003138, result=@0x7f6fe968fdd8: 0x7f6df00063f8, setup_tables_done_option=0, 
    res=@0x7f6fe968fdd4: 0, optimize_after_tianmu=@0x7f6fe968fdcc: 0, tianmu_free_join=@0x7f6fe968fdd0: 1, with_insert=0) at /root/work/stonedb-dev-20221123/storage/tianmu/core/engine_execute.cpp:231
#6  0x0000000002d6c1bf in Tianmu::handler::ha_my_tianmu_query (thd=0x7f6df0000e10, lex=0x7f6df0003138, result_output=@0x7f6fe968fdd8: 0x7f6df00063f8, setup_tables_done_option=0, res=@0x7f6fe968fdd4: 0, 
    optimize_after_tianmu=@0x7f6fe968fdcc: 0, tianmu_free_join=@0x7f6fe968fdd0: 1, with_insert=0) at /root/work/stonedb-dev-20221123/storage/tianmu/handler/ha_my_tianmu.cpp:88
#7  0x00000000023aeb83 in execute_sqlcom_select (thd=0x7f6df0000e10, all_tables=0x7f6df0005c80) at /root/work/stonedb-dev-20221123/sql/sql_parse.cc:5184
#8  0x00000000023a7f19 in mysql_execute_command (thd=0x7f6df0000e10, first_level=true) at /root/work/stonedb-dev-20221123/sql/sql_parse.cc:2831
#9  0x00000000023afbe9 in mysql_parse (thd=0x7f6df0000e10, parser_state=0x7f6fe9690f90) at /root/work/stonedb-dev-20221123/sql/sql_parse.cc:5622
#10 0x00000000023a4cf4 in dispatch_command (thd=0x7f6df0000e10, com_data=0x7f6fe9691730, command=COM_QUERY) at /root/work/stonedb-dev-20221123/sql/sql_parse.cc:1495
#11 0x00000000023a3b35 in do_command (thd=0x7f6df0000e10) at /root/work/stonedb-dev-20221123/sql/sql_parse.cc:1034
#12 0x00000000024d51c9 in handle_connection (arg=0x8437ac0) at /root/work/stonedb-dev-20221123/sql/conn_handler/connection_handler_per_thread.cc:313
#13 0x0000000002ba24e8 in pfs_spawn_thread (arg=0x7ea2980) at /root/work/stonedb-dev-20221123/storage/perfschema/pfs.cc:2197
#14 0x00007f6ff3d481ca in start_thread () from /lib64/libpthread.so.0
#15 0x00007f6ff12b2e73 in clone () from /lib64/libc.so.6


```

**Comment by adofsauron** [comment] 2022-11-24 10:31
### mysql5.7 also does not execute two escapes in NO_BACKSLASH_ESCAPES mode

```sql

mysql> show create table BUG_12595\G
*************************** 1. row ***************************
       Table: BUG_12595
Create Table: CREATE TABLE `BUG_12595` (
  `a` varchar(100) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
1 row in set (0.00 sec)

mysql> SELECT * FROM BUG_12595 WHERE a LIKE 'hakan\%' ESCAPE '\\';
ERROR 1210 (HY000): Incorrect arguments to ESCAPE


```

**Comment by adofsauron** [comment] 2022-11-24 10:33
![C225A562-86A4-4cf7-A373-A3A38CFF7404](https://user-images.githubusercontent.com/3915817/203763017-9fb711e3-6293-4a41-a4c6-ae6e69902142.png)



```bash

[root@localhost ~]# mysql
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 2
Server version: 5.6.51 MySQL Community Server (GPL)

Copyright (c) 2000, 2021, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> use d42
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
mysql> SET @@SQL_MODE='NO_BACKSLASH_ESCAPES';
Query OK, 0 rows affected (0.00 sec)

mysql> SHOW LOCAL VARIABLES LIKE 'SQL_MODE';
+---------------+----------------------+
| Variable_name | Value                |
+---------------+----------------------+
| sql_mode      | NO_BACKSLASH_ESCAPES |
+---------------+----------------------+
1 row in set (0.00 sec)

mysql> 
mysql> CREATE TABLE BUG_12595(a varchar(100))engine=stonedb;
ERROR 1050 (42S01): Table 'BUG_12595' already exists
mysql> INSERT INTO BUG_12595 VALUES ('hakan%'), ('hakank'), ("ha%an");
Query OK, 3 rows affected (0.01 sec)
Records: 3  Duplicates: 0  Warnings: 0

mysql> show create table BUG_12595;
+-----------+---------------------------------------------------------------------------------------------------+
| Table     | Create Table                                                                                      |
+-----------+---------------------------------------------------------------------------------------------------+
| BUG_12595 | CREATE TABLE `BUG_12595` (
  `a` varchar(100) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1 |
+-----------+---------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)



mysql> 
mysql> SELECT * FROM BUG_12595 WHERE a LIKE 'hakan\%' ESCAPE '\\';
ERROR 1210 (HY000): Incorrect arguments to ESCAPE
mysql> 

```


```sql

mysql> show create table BUG_12595;
+-----------+---------------------------------------------------------------------------------------------------+
| Table     | Create Table                                                                                      |
+-----------+---------------------------------------------------------------------------------------------------+
| BUG_12595 | CREATE TABLE `BUG_12595` (
  `a` varchar(100) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1 |
+-----------+---------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

mysql> SELECT * FROM test1 WHERE a LIKE 'hakan%' ESCAPE '';
ERROR 1210 (HY000): Incorrect arguments to ESCAPE
mysql> SELECT * FROM test1 WHERE a LIKE 'hakan\%' ESCAPE '\\';
ERROR 1210 (HY000): Incorrect arguments to ESCAPE
mysql> SELECT * FROM test1 WHERE a LIKE 'hakan\n%' ESCAPE '\n';
ERROR 1210 (HY000): Incorrect arguments to ESCAPE


```

**Comment by adofsauron** [comment] 2022-11-24 12:29
This ISSUE is not a problem. It is the human cognitive error caused by the wrong test method, which will not be solved

**Comment by RingsC** [comment] 2022-11-24 12:33
@shangyanwen , you should verify what said by @adofsauron , Thanks.

**Comment by RingsC** [comment] 2022-11-28 02:09
We have verified that the result is OK.  but when you use different SQL_MODE, it will generate different result. Therefore, we close it now.

**Closed as completed** 2022-11-28 03:01 UTC
Labels: A-bug
