### ISSUE TITLE
feat(stonedb):  Replace `Query_result::prepare2()` with ` Query_result::start_execution`.

### ISSUE THREAD

**Issue by andyli029** [stoneatom/stonedb#539] opened 2022-09-22 06:59 UTC
**Is your feature request related to a problem? Please describe.**

In previous version, we are also using `prepare2()` in optimization phase. But, in mysql 8.0, `prepare2()` was changed to `start_execution`, the change logs were listed below for reference. Therefore, we should change `prepare2()` to `start_execution` too. 

Query_result::prepare2() is deleted by MySQL 8.0
(engine_execute.cpp/optimize_select）

Analyze、Evaluate and Improve related functions.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by DandreChen** [comment] 2022-09-22 08:23
porting from @RingsC :
5.7 prepare2
```
int Query_result_insert::prepare2()
{
DBUG_ENTER("Query_result_insert::prepare2");
if (thd->locked_tables_mode <= LTM_LOCK_TABLES &&
!thd->lex->describe)
{
assert(!bulk_insert_started);
// TODO: Is there no better estimation than 0 == Unknown number of rows?
table->file->ha_start_bulk_insert((ha_rows) 0);
bulk_insert_started= true;
}
DBUG_RETURN(0);
}
```

And the others do nothing.

**Comment by DandreChen** [comment] 2022-09-22 08:23
porting from @RingsC 

MySQL change log for prepare2 and prepare is listed as following for ur reference.
--------------------
commit b28a90b8f23e3abdbd8f1b2b9a3765e577255673
Author: Roy Lyseng <roy.lyseng@oracle.com>
Date:   Wed Dec 7 14:08:12 2016 +0100

    Bug#25183521: Rename a few fields in Query_result class

    Some functions are given more comprehensive names:

    - initialize_tables() is renamed to optimize()
      This function is called during the optimization stage to create
      specific objects that are needed for execution.

    **- prepare2() is renamed to start_execution()
      Despite the name, this function is actually called at start of
      execution, after optimization.
      So, we can eliminate a few "prepare() && prepare2()" constructs
      because they target different phases.**

    Fields used in prepared DELETE and UPDATE statements change semantics
    slightly:

    - do_delete replaced with delete_completed.
    - do_update replaced with update_completed.

    These booleans will start out in false state and get set to true when
    the operation is actually completed.
    For repeated executions, they will likely be set to false in appropriate
    start_execution() function.

    In addition, some arguments and return values are cleaned up.
    Return values are changed from int to bool.

commit 928e8bcdf0c8340b672f4c7cc695be38d3b01c3d
Author: Mattias Jonsson <mattias.jonsson@oracle.com>
Date:   Sat Jan 12 00:45:39 2013 +0100

    Bug#16076275: HANDLER::HA_END_BULK_IN CREATE TABLE .. SELECT,
    STATEMENT BINLOGGING

    Regression from wl#4443.

    Due to reorganization of select_create::prepare2()/create_table_from_items.

    If locking fails, the temporary table is dropped, but the pointer 'table' is
    not reset. So during select_insert::abort_result_set() since table is not NULL
    it tries to use the pointer which is no longer valid.

    Fixed by resetting table to NULL after it was dropped.

commit 917bc529d9c067fbbac68773e33cf8683f08b84e
Author: Mattias Jonsson <mattias.jonsson@oracle.com>
Date:   Sat May 19 01:11:36 2012 +0200

    WL#4443
    Fix for CREATE SELECT and delayed locking.

    To be consistent with the protocol for locking
    and THD::decide_logging_format(), we postpone
    locking of target table to after all locks has been
    taken on the source tables.

    i.e. we create the table in create_select::prepare()
    and lock it in create_select::prepare2().
    prepare() is called from JOIN::prepare() and
    prepare2() from JOIN::exec().

commit da7470afb153cf9df6c8b864a5dd03eaa73a3f74
Author: evgen@moonbone.local <>
Date:   Mon Nov 19 21:05:17 2007 +0000
    engine->start_bulk_insert function was called twice. On the first call
    On the first call MyISAM disabled all non-unique indexes and on the second
    call it decides to not re-enable them because all indexes was disabled.
    Due to this no indexes was actually created during CREATE TABLE thus
    producing crashed table.

    Now the select_inset class has is_bulk_insert_mode flag which prevents
    calling the start_bulk_insert function twice.
    The flag is set in the select_create::prepare, select_insert::prepare2
    functions and the select_insert class constructor.
    The flag is reset in the select_insert::send_eof function.

**Comment by DandreChen** [comment] 2022-09-22 12:09
used in 5.7,  as below:
```
bool JOIN::prepare_result()
{
  DBUG_ENTER("JOIN::prepare_result");

  error= 0;
  // Create result tables for materialized views/derived tables
  if (select_lex->materialized_derived_table_count && !zero_result_cause)
  {
    for (TABLE_LIST *tl= select_lex->leaf_tables; tl; tl= tl->next_leaf)
    {
      if (tl->is_view_or_derived() && tl->create_derived(thd))
        goto err;                 /* purecov: inspected */
    }
  }

  if (select_lex->query_result()->prepare2())
    goto err;

  if ((select_lex->active_options() & OPTION_SCHEMA_TABLE) &&
      get_schema_tables_result(this, PROCESSED_BY_JOIN_EXEC))
    goto err;

  DBUG_RETURN(false);

err:
  error= 1;
  DBUG_RETURN(true);
}

```

**Comment by DandreChen** [comment] 2022-09-22 12:16
start_execution used in 8.0, as below:

```
bool JOIN::prepare_result() {
  DBUG_TRACE;

  error = 0;

  if (query_block->query_result()->start_execution(thd)) goto err;

  return false;

err:
  error = 1;
  return true;
}
```

**Comment by DandreChen** [comment] 2022-09-22 12:20
8.0 start_execution()
```
bool Query_result_insert::start_execution(THD *thd) {
  DBUG_TRACE;

  table = thd->lex->insert_table_leaf->table;
  restore_record(table, s->default_values);  // Get empty record
  table->next_number_field = table->found_next_number_field;

  const enum_duplicates duplicate_handling = info.get_duplicate_handling();

  if (info.add_function_default_columns(table, table->write_set)) {
    return true;
  }
  if ((duplicate_handling == DUP_UPDATE) &&
      update.add_function_default_columns(table, table->write_set))
    return true;

  if (thd->slave_thread) {
    /* Get SQL thread's rli, even for a slave worker thread */
    Relay_log_info *c_rli = thd->rli_slave->get_c_rli();
    assert(c_rli != nullptr);
    if (duplicate_handling == DUP_UPDATE &&
        table->next_number_field != nullptr &&
        rpl_master_has_bug(c_rli, 24432, true, nullptr, nullptr))
      return true;
  }

  thd->num_truncated_fields = 0;
  if (thd->lex->is_ignore() || duplicate_handling != DUP_ERROR)
    table->file->ha_extra(HA_EXTRA_IGNORE_DUP_KEY);
  if (duplicate_handling == DUP_REPLACE &&
      (!table->triggers || !table->triggers->has_delete_triggers()))
    table->file->ha_extra(HA_EXTRA_WRITE_CAN_REPLACE);
  if (duplicate_handling == DUP_UPDATE)
    table->file->ha_extra(HA_EXTRA_INSERT_WITH_UPDATE);

  prepare_triggers_for_insert_stmt(thd, table);

  for (Field **next_field = table->field; *next_field; ++next_field) {
    (*next_field)->reset_warnings();
    (*next_field)->reset_tmp_null();
  }

  if (thd->locked_tables_mode <= LTM_LOCK_TABLES && !thd->lex->is_explain()) {
    assert(!bulk_insert_started);
    // TODO: Is there no better estimation than 0 == Unknown number of rows?
    table->file->ha_start_bulk_insert((ha_rows)0);
    bulk_insert_started = true;
  }
  info.reset_counters();

  return false;
}
```

**Comment by DandreChen** [comment] 2022-09-26 08:29
ACK

**Comment by DandreChen** [comment] 2022-10-05 10:46
start_execution() used in select

```
bool Query_expression::ExecuteIteratorQuery(THD *thd) {
...

  mem_root_deque<Item *> *fields = get_field_list();
  Query_result *query_result = this->query_result();
  assert(query_result != nullptr);

  if (query_result->start_execution(thd)) return true;

  if (query_result->send_result_set_metadata(
          thd, *fields, Protocol::SEND_NUM_ROWS | Protocol::SEND_EOF)) {
    return true;
  }

  set_executed();

  // Hand over the query to the secondary engine if needed.
  if (first_query_block()->join->override_executor_func != nullptr) {
    thd->current_found_rows = 0;
    for (Query_block *select = first_query_block(); select != nullptr;
         select = select->next_query_block()) {
      if (select->join->override_executor_func(select->join, query_result)) {
        return true;
      }
      thd->current_found_rows += select->join->send_records;
    }
    const bool calc_found_rows =
        (first_query_block()->active_options() & OPTION_FOUND_ROWS);
    if (!calc_found_rows) {
      // This is for backwards compatibility reasons only;
      // we have documented that without SQL_CALC_FOUND_ROWS,
      // we return the actual number of rows returned.
      thd->current_found_rows =
          std::min(thd->current_found_rows, select_limit_cnt);
    }
    return query_result->send_eof(thd);
  }

 ...
}
```

**Comment by DandreChen** [comment] 2022-10-05 10:52
start_execution() used in explain
```
bool JOIN::prepare_result() {
  DBUG_TRACE;

  error = 0;

  if (query_block->query_result()->start_execution(thd)) goto err;

  return false;

err:
  error = 1;
  return true;
}

```

```
bool explain_query_specification(THD *explain_thd, const THD *query_thd,
                                 Query_block *query_block,
                                 enum_parsing_context ctx) {
....
  switch (join->get_plan_state()) {
    case JOIN::ZERO_RESULT: {
      ret = explain_no_table(explain_thd, query_thd, query_block,
                             join->zero_result_cause, ctx);
      break;
    }
    case JOIN::NO_TABLES: {
      if (query_plan->get_lex()->insert_table_leaf &&
          query_plan->get_lex()->insert_table_leaf->query_block ==
              query_block) {
        // INSERT/REPLACE SELECT ... FROM dual
        ret = Explain_table(
                  explain_thd, query_thd, query_block,
                  query_plan->get_lex()->insert_table_leaf->table, JT_UNKNOWN,
                  /*quick=*/nullptr, /*condition=*/nullptr, MAX_KEY,
                  HA_POS_ERROR, false, false,
                  (query_plan->get_lex()->sql_command == SQLCOM_INSERT_SELECT
                       ? MT_INSERT
                       : MT_REPLACE),
                  false, nullptr)
                  .send() ||
              explain_thd->is_error();
      } else
        ret = explain_no_table(explain_thd, query_thd, query_block,
                               "No tables used", CTX_JOIN);

      break;
    }
    case JOIN::PLAN_READY: {
      /*
        (1) If this connection is explaining its own query
        (2) and it hasn't already prepared the JOIN's result,
        then we need to prepare it (for example, to materialize I_S tables).
      */
      if (!other && !join->is_executed() && join->prepare_result())
        return true; /* purecov: inspected */

...
}
```

**Closed as completed** 2022-10-14 16:59 UTC
Labels: A-feature, C-stonedb-8.0
