### ISSUE TITLE
docker make fatal error: boost/algorithm/string.hpp: No such file or directorybug: 

### ISSUE THREAD

**Issue by xshiyun** [stoneatom/stonedb#256] opened 2022-07-19 11:02 UTC
### Describe the problem
for mysql 5.7
docker make
`/home/stonedb/storage/stonedb/common/data_format.cpp:23:10: fatal error: boost/algorithm/string.hpp: No such file or directory`

### Are you interested in submitting a PR to solve the problem?

- [ ] Yes, I will!

**Comment by zsp108** [comment] 2022-07-20 06:05
hi，how to build stonedb in the docker build-environment?
use docker pull?
or docker build? 
please tell me your reproduction steps

**Comment by CHENEY-LANCE** [comment] 2022-07-20 06:53
> hi，how to build stonedb in the docker build-environment? use docker pull? or docker build? please tell me your reproduction steps

你好，我也遇到这个情况了。docker已经搭建成功， cmake之后，make编译的时候 报错

/home/atomstore2022/storage/stonedb/common/data_format.cpp:23:10: fatal error: boost/algorithm/string.hpp: No such file or directory
 #include <boost/algorithm/string.hpp>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [storage/stonedb/CMakeFiles/stonedb.dir/common/data_format.cpp.o] Error 1
make[1]: *** [storage/stonedb/CMakeFiles/stonedb.dir/all] Error 2

**Comment by xshiyun** [comment] 2022-07-20 09:09
> 

docker pull

**Comment by xshiyun** [comment] 2022-07-20 09:09
> hi，how to build stonedb in the docker build-environment? use docker pull? or docker build? please tell me your reproduction steps

docker pull

**Comment by zsp108** [comment] 2022-07-20 11:07
@xshiyun @CHENEY-LANCE 

Clean up the old cmake file and try again
```
cmake ../ \
-DCMAKE_BUILD_TYPE=RelWithDebInfo \
-DCMAKE_INSTALL_PREFIX=/stonedb56/install \
-DMYSQL_DATADIR=/stonedb56/install/data \
-DSYSCONFDIR=/stonedb56/install \
-DMYSQL_UNIX_ADDR=/stonedb56/install/tmp/mysql.sock \
-DWITH_EMBEDDED_SERVER=OFF \
-DWITH_STONEDB_STORAGE_ENGINE=1 \
-DWITH_MYISAM_STORAGE_ENGINE=1 \
-DWITH_INNOBASE_STORAGE_ENGINE=1 \
-DWITH_PARTITION_STORAGE_ENGINE=1 \
-DMYSQL_TCP_PORT=3306 \
-DENABLED_LOCAL_INFILE=1 \
-DEXTRA_CHARSETS=all \
-DDEFAULT_CHARSET=utf8 \
-DDEFAULT_COLLATION=utf8_general_ci \
-DDOWNLOAD_BOOST=0 \
-DWITH_BOOST=/usr/local/stonedb-boost/
```

Or you can use quick build script we provided, in ``scripts/stonedb_build.sh``

**Comment by CHENEY-LANCE** [comment] 2022-07-21 05:50
> ORT=3306 \
> -DENABLED_LOCAL_INFILE=1 \
> -DEXTRA_CHARSETS=all \
> -DDEFAULT_CHARSET=utf8 \
> -DDEFAULT_COLLATION=utf8_general_ci \
> -DDOWNLOAD_BOOST=0 \
> -DWITH_BOOST=/usr/local/stonedb-boost/

After using the script，  I have solved the previous problems, but there are new problems that need you to help me have a look.Sorry to trouble you.


`[ 72%] Generating xdr_gen/xcom_vp.h, xdr_gen/xcom_vp_xdr.c, xdr_gen/xcom_vp_platform.h
cannot find C preprocessor: cpp
/usr/bin/rpcgen: C preprocessor failed with exit code 1
make[2]: *** [rapid/plugin/group_replication/xdr_gen/xcom_vp.h] Error 1
make[1]: *** [rapid/plugin/group_replication/CMakeFiles/group_replication.dir/all] Error 2
make: *** [all] Error 2
current dir is /home/atomstore2022/build/build_stonedb-5.7_x86_64_CentOS7.9.2009_Debug_2022-07-21_03-34-52
`

**Comment by CHENEY-LANCE** [comment] 2022-07-21 05:52
> @xshiyun @CHENEY-LANCE
> 
> Clean up the old cmake file and try again
> 
> ```
> cmake ../ \
> -DCMAKE_BUILD_TYPE=RelWithDebInfo \
> -DCMAKE_INSTALL_PREFIX=/stonedb56/install \
> -DMYSQL_DATADIR=/stonedb56/install/data \
> -DSYSCONFDIR=/stonedb56/install \
> -DMYSQL_UNIX_ADDR=/stonedb56/install/tmp/mysql.sock \
> -DWITH_EMBEDDED_SERVER=OFF \
> -DWITH_STONEDB_STORAGE_ENGINE=1 \
> -DWITH_MYISAM_STORAGE_ENGINE=1 \
> -DWITH_INNOBASE_STORAGE_ENGINE=1 \
> -DWITH_PARTITION_STORAGE_ENGINE=1 \
> -DMYSQL_TCP_PORT=3306 \
> -DENABLED_LOCAL_INFILE=1 \
> -DEXTRA_CHARSETS=all \
> -DDEFAULT_CHARSET=utf8 \
> -DDEFAULT_COLLATION=utf8_general_ci \
> -DDOWNLOAD_BOOST=0 \
> -DWITH_BOOST=/usr/local/stonedb-boost/
> ```
> 
> Or you can use quick build script we provided, in `scripts/stonedb_build.sh`

After using the script， I have solved the previous problems, but there are new problems that need you to help me have a look.Sorry to trouble you.

`[ 72%] Generating xdr_gen/xcom_vp.h, xdr_gen/xcom_vp_xdr.c, xdr_gen/xcom_vp_platform.h
cannot find C preprocessor: cpp
/usr/bin/rpcgen: C preprocessor failed with exit code 1
make[2]: *** [rapid/plugin/group_replication/xdr_gen/xcom_vp.h] Error 1
make[1]: *** [rapid/plugin/group_replication/CMakeFiles/group_replication.dir/all] Error 2
make: *** [all] Error 2
current dir is /home/atomstore2022/build/build_stonedb-5.7_x86_64_CentOS7.9.2009_Debug_2022-07-21_03-34-52
`

**Comment by CHENEY-LANCE** [comment] 2022-07-21 05:55
> @xshiyun @CHENEY-LANCE
> 
> Clean up the old cmake file and try again
> 
> ```
> cmake ../ \
> -DCMAKE_BUILD_TYPE=RelWithDebInfo \
> -DCMAKE_INSTALL_PREFIX=/stonedb56/install \
> -DMYSQL_DATADIR=/stonedb56/install/data \
> -DSYSCONFDIR=/stonedb56/install \
> -DMYSQL_UNIX_ADDR=/stonedb56/install/tmp/mysql.sock \
> -DWITH_EMBEDDED_SERVER=OFF \
> -DWITH_STONEDB_STORAGE_ENGINE=1 \
> -DWITH_MYISAM_STORAGE_ENGINE=1 \
> -DWITH_INNOBASE_STORAGE_ENGINE=1 \
> -DWITH_PARTITION_STORAGE_ENGINE=1 \
> -DMYSQL_TCP_PORT=3306 \
> -DENABLED_LOCAL_INFILE=1 \
> -DEXTRA_CHARSETS=all \
> -DDEFAULT_CHARSET=utf8 \
> -DDEFAULT_COLLATION=utf8_general_ci \
> -DDOWNLOAD_BOOST=0 \
> -DWITH_BOOST=/usr/local/stonedb-boost/
> ```
> 
> Or you can use quick build script we provided, in `scripts/stonedb_build.sh`

After using the script， I have solved the previous problems, but there are new problems that need you to help me have a look.Sorry to trouble you.

```
[ 72%] Generating xdr_gen/xcom_vp.h, xdr_gen/xcom_vp_xdr.c, xdr_gen/xcom_vp_platform.h
cannot find C preprocessor: cpp
/usr/bin/rpcgen: C preprocessor failed with exit code 1
make[2]: *** [rapid/plugin/group_replication/xdr_gen/xcom_vp.h] Error 1
make[1]: *** [rapid/plugin/group_replication/CMakeFiles/group_replication.dir/all] Error 2
make: *** [all] Error 2
current dir is /home/atomstore2022/build/build_stonedb-5.7_x86_64_CentOS7.9.2009_Debug_2022-07-21_03-34-52
```

**Comment by xshiyun** [comment] 2022-07-21 07:18
> > @xshiyun @CHENEY-LANCE
> > Clean up the old cmake file and try again
> > ```
> > cmake ../ \
> > -DCMAKE_BUILD_TYPE=RelWithDebInfo \
> > -DCMAKE_INSTALL_PREFIX=/stonedb56/install \
> > -DMYSQL_DATADIR=/stonedb56/install/data \
> > -DSYSCONFDIR=/stonedb56/install \
> > -DMYSQL_UNIX_ADDR=/stonedb56/install/tmp/mysql.sock \
> > -DWITH_EMBEDDED_SERVER=OFF \
> > -DWITH_STONEDB_STORAGE_ENGINE=1 \
> > -DWITH_MYISAM_STORAGE_ENGINE=1 \
> > -DWITH_INNOBASE_STORAGE_ENGINE=1 \
> > -DWITH_PARTITION_STORAGE_ENGINE=1 \
> > -DMYSQL_TCP_PORT=3306 \
> > -DENABLED_LOCAL_INFILE=1 \
> > -DEXTRA_CHARSETS=all \
> > -DDEFAULT_CHARSET=utf8 \
> > -DDEFAULT_COLLATION=utf8_general_ci \
> > -DDOWNLOAD_BOOST=0 \
> > -DWITH_BOOST=/usr/local/stonedb-boost/
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Or you can use quick build script we provided, in `scripts/stonedb_build.sh`
> 
> After using the script， I have solved the previous problems, but there are new problems that need you to help me have a look.Sorry to trouble you.
> 
> ```
> [ 72%] Generating xdr_gen/xcom_vp.h, xdr_gen/xcom_vp_xdr.c, xdr_gen/xcom_vp_platform.h
> cannot find C preprocessor: cpp
> /usr/bin/rpcgen: C preprocessor failed with exit code 1
> make[2]: *** [rapid/plugin/group_replication/xdr_gen/xcom_vp.h] Error 1
> make[1]: *** [rapid/plugin/group_replication/CMakeFiles/group_replication.dir/all] Error 2
> make: *** [all] Error 2
> current dir is /home/atomstore2022/build/build_stonedb-5.7_x86_64_CentOS7.9.2009_Debug_2022-07-21_03-34-52
> ```

同样的问题

**Comment by zsp108** [comment] 2022-07-25 02:42
> > @xshiyun @CHENEY-LANCE
> > Clean up the old cmake file and try again
> > ```
> > cmake ../ \
> > -DCMAKE_BUILD_TYPE=RelWithDebInfo \
> > -DCMAKE_INSTALL_PREFIX=/stonedb56/install \
> > -DMYSQL_DATADIR=/stonedb56/install/data \
> > -DSYSCONFDIR=/stonedb56/install \
> > -DMYSQL_UNIX_ADDR=/stonedb56/install/tmp/mysql.sock \
> > -DWITH_EMBEDDED_SERVER=OFF \
> > -DWITH_STONEDB_STORAGE_ENGINE=1 \
> > -DWITH_MYISAM_STORAGE_ENGINE=1 \
> > -DWITH_INNOBASE_STORAGE_ENGINE=1 \
> > -DWITH_PARTITION_STORAGE_ENGINE=1 \
> > -DMYSQL_TCP_PORT=3306 \
> > -DENABLED_LOCAL_INFILE=1 \
> > -DEXTRA_CHARSETS=all \
> > -DDEFAULT_CHARSET=utf8 \
> > -DDEFAULT_COLLATION=utf8_general_ci \
> > -DDOWNLOAD_BOOST=0 \
> > -DWITH_BOOST=/usr/local/stonedb-boost/
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Or you can use quick build script we provided, in `scripts/stonedb_build.sh`
> 
> After using the script， I have solved the previous problems, but there are new problems that need you to help me have a look.Sorry to trouble you.
> 
> ```
> [ 72%] Generating xdr_gen/xcom_vp.h, xdr_gen/xcom_vp_xdr.c, xdr_gen/xcom_vp_platform.h
> cannot find C preprocessor: cpp
> /usr/bin/rpcgen: C preprocessor failed with exit code 1
> make[2]: *** [rapid/plugin/group_replication/xdr_gen/xcom_vp.h] Error 1
> make[1]: *** [rapid/plugin/group_replication/CMakeFiles/group_replication.dir/all] Error 2
> make: *** [all] Error 2
> current dir is /home/atomstore2022/build/build_stonedb-5.7_x86_64_CentOS7.9.2009_Debug_2022-07-21_03-34-52
> ```

This is missing cpp, you can run `` ln -s /opt/rh/devtoolset-7/root/bin/cpp /lib/cpp `` in the container
or
pull the latest image?
```
docker pull stoneatom/stonedb_buildenv:latest
```
@CHENEY-LANCE @xshiyun

**Comment by CHENEY-LANCE** [comment] 2022-07-26 02:10
@zsp108 
Excuse me，I redeployed，
`docker pull stoneatom/stonedb_buildenv:latest`
according to the compilation manual,
`https://stonedb.io/zh/docs/developer-guide/compiling-methods/compile-using-docker`

There is no `reinstall.sh` script for ` /stonedb56/` in the container.
But this script is found in the `/stonedb57/ ` and  `/home/stonedb/install_scripts ` of the container.The same error is reported when running the scrip.
```
[root@8af46c73e4eb install_scripts]# ./reinstall.sh
./mysql_server: line 211: my_print_defaults: command not found
/etc/redhat-lsb/lsb_log_message: line 3: /etc/init.d/functions: No such file or directory
Stonedb server PID file could not be found!/etc/redhat-lsb/lsb_log_message: line 16: failure: command not found

clean the directories...
run mysqld initialize ...
./reinstall.sh: line 32: ./bin/mysqld: No such file or directory
start the instance...
+ basedir=
+ datadir=
+ service_startup_timeout=900
+ lockdir=/var/lock/subsys
+ lock_file_path=/var/lock/subsys/mysql
+ mysqld_pid_file_path=
+ test -z ''
+ basedir=/stonedb57/install
+ bindir=/stonedb57/install/bin
+ test -z ''
+ datadir=/stonedb57/install/data
+ sbindir=/stonedb57/install/bin
+ libexecdir=/stonedb57/install/bin
+ datadir_set=
+ lsb_functions=/lib/lsb/init-functions
+ test -f /lib/lsb/init-functions
+ . /lib/lsb/init-functions
+ PATH=/sbin:/usr/sbin:/bin:/usr/bin:/stonedb57/install/bin
+ export PATH
+ mode=start
+ '[' 1 -ge 1 ']'
+ shift
+ case `echo "testing\c"`,`echo -n testing` in
++ echo 'testing\c'
++ echo -n testing
+ echo_n=-n
+ echo_c=
+ test -x /stonedb57/install/bin/my_print_defaults
+ conf=/etc/my.cnf
+ print_defaults=
+ test -r /etc/my.cnf
+ subpat='^[^=]*basedir[^=]*=\(.*\)$'
++ sed -e '/^[^=]*basedir[^=]*=\(.*\)$/!d' -e 's//\1/' /etc/my.cnf
+ dirs=
+ test -z ''
+ print_defaults=my_print_defaults
+ user=mysql
+ extra_args=
+ test -r /stonedb57/install/my.cnf
+ extra_args='-e /stonedb57/install/my.cnf'
++ my_print_defaults -e /stonedb57/install/my.cnf mysqld server mysql_server mysql.server
./mysql_server: line 211: my_print_defaults: command not found
+ parse_server_arguments
+ parse_server_arguments
+ test -z ''
++ hostname
+ mysqld_pid_file_path=/stonedb57/install/data/8af46c73e4eb.pid
+ '[' -f /etc/default/mysql ']'
+ '[' -f /etc/sysconfig/mysql ']'
+ '[' -f /etc/conf.d/mysql ']'
+ case "$mode" in
+ cd /stonedb57/install
+ echo -n 'Starting Stonedb'
Starting Stonedb+ test -x /stonedb57/install/bin/mysqld_safe
+ log_failure_msg 'Couldn'\''t find Stonedb server (/stonedb57/install/bin/mysqld_safe)'
+ /etc/redhat-lsb/lsb_log_message failure 'Couldn'\''t find Stonedb server (/stonedb57/install/bin/mysqld_safe)'
/etc/redhat-lsb/lsb_log_message: line 3: /etc/init.d/functions: No such file or directory
Couldn't find Stonedb server (/stonedb57/install/bin/mysqld_safe)/etc/redhat-lsb/lsb_log_message: line 16: failure: command not found

+ exit 0
```



I tried `Quick Deployment in a Docker Container`，
`docker pull stoneatom/stonedb:v0.1`
Errors are reported as follows
```
root@2823c9ae0d75:/# /stonedb56/install/bin/mysql -uroot -pstonedb123
Warning: Using a password on the command line interface can be insecure.
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/stonedb56/install/tmp/mysql.sock' (2)
root@2823c9ae0d75:/# /stonedb56/install/bin/mysql -uroot -p
Enter password:
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/stonedb56/install/tmp/mysql.sock' (2)
```

**Comment by zsp108** [comment] 2022-07-26 06:22
> @zsp108 Excuse me，I redeployed， `docker pull stoneatom/stonedb_buildenv:latest` according to the compilation manual, `https://stonedb.io/zh/docs/developer-guide/compiling-methods/compile-using-docker`
> 
> There is no `reinstall.sh` script for ` /stonedb56/` in the container. But this script is found in the `/stonedb57/ ` and `/home/stonedb/install_scripts ` of the container.The same error is reported when running the scrip.
> 
> ```
> [root@8af46c73e4eb install_scripts]# ./reinstall.sh
> ./mysql_server: line 211: my_print_defaults: command not found
> /etc/redhat-lsb/lsb_log_message: line 3: /etc/init.d/functions: No such file or directory
> Stonedb server PID file could not be found!/etc/redhat-lsb/lsb_log_message: line 16: failure: command not found
> 
> clean the directories...
> run mysqld initialize ...
> ./reinstall.sh: line 32: ./bin/mysqld: No such file or directory
> start the instance...
> + basedir=
> + datadir=
> + service_startup_timeout=900
> + lockdir=/var/lock/subsys
> + lock_file_path=/var/lock/subsys/mysql
> + mysqld_pid_file_path=
> + test -z ''
> + basedir=/stonedb57/install
> + bindir=/stonedb57/install/bin
> + test -z ''
> + datadir=/stonedb57/install/data
> + sbindir=/stonedb57/install/bin
> + libexecdir=/stonedb57/install/bin
> + datadir_set=
> + lsb_functions=/lib/lsb/init-functions
> + test -f /lib/lsb/init-functions
> + . /lib/lsb/init-functions
> + PATH=/sbin:/usr/sbin:/bin:/usr/bin:/stonedb57/install/bin
> + export PATH
> + mode=start
> + '[' 1 -ge 1 ']'
> + shift
> + case `echo "testing\c"`,`echo -n testing` in
> ++ echo 'testing\c'
> ++ echo -n testing
> + echo_n=-n
> + echo_c=
> + test -x /stonedb57/install/bin/my_print_defaults
> + conf=/etc/my.cnf
> + print_defaults=
> + test -r /etc/my.cnf
> + subpat='^[^=]*basedir[^=]*=\(.*\)$'
> ++ sed -e '/^[^=]*basedir[^=]*=\(.*\)$/!d' -e 's//\1/' /etc/my.cnf
> + dirs=
> + test -z ''
> + print_defaults=my_print_defaults
> + user=mysql
> + extra_args=
> + test -r /stonedb57/install/my.cnf
> + extra_args='-e /stonedb57/install/my.cnf'
> ++ my_print_defaults -e /stonedb57/install/my.cnf mysqld server mysql_server mysql.server
> ./mysql_server: line 211: my_print_defaults: command not found
> + parse_server_arguments
> + parse_server_arguments
> + test -z ''
> ++ hostname
> + mysqld_pid_file_path=/stonedb57/install/data/8af46c73e4eb.pid
> + '[' -f /etc/default/mysql ']'
> + '[' -f /etc/sysconfig/mysql ']'
> + '[' -f /etc/conf.d/mysql ']'
> + case "$mode" in
> + cd /stonedb57/install
> + echo -n 'Starting Stonedb'
> Starting Stonedb+ test -x /stonedb57/install/bin/mysqld_safe
> + log_failure_msg 'Couldn'\''t find Stonedb server (/stonedb57/install/bin/mysqld_safe)'
> + /etc/redhat-lsb/lsb_log_message failure 'Couldn'\''t find Stonedb server (/stonedb57/install/bin/mysqld_safe)'
> /etc/redhat-lsb/lsb_log_message: line 3: /etc/init.d/functions: No such file or directory
> Couldn't find Stonedb server (/stonedb57/install/bin/mysqld_safe)/etc/redhat-lsb/lsb_log_message: line 16: failure: command not found
> 
> + exit 0
> ```
> 
> I tried `Quick Deployment in a Docker Container`， `docker pull stoneatom/stonedb:v0.1` Errors are reported as follows
> 
> ```
> root@2823c9ae0d75:/# /stonedb56/install/bin/mysql -uroot -pstonedb123
> Warning: Using a password on the command line interface can be insecure.
> ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/stonedb56/install/tmp/mysql.sock' (2)
> root@2823c9ae0d75:/# /stonedb56/install/bin/mysql -uroot -p
> Enter password:
> ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/stonedb56/install/tmp/mysql.sock' (2)
> ```

check /stonedb57/install/bin/mysqld? and 
```
./reinstall.sh: line 32: ./bin/mysqld: No such file or directory
```

The “/etc/redhat-lsb/lsb_log_message: line 3: /etc/init.d/functions: No such file or directory” error message is returned the initscripts dependency is missing,You can run `` yum install initscripts`` to install the dependency.

**Comment by CHENEY-LANCE** [comment] 2022-07-29 03:24
According to the manual deployment, the latest version
`docker pull stoneatom/stonedb_buildenv:latest`
the /stonedb57/install  does not contain /bin/ folder, but /stone56/ does.
 How should I deploy it?

**Comment by zsp108** [comment] 2022-07-29 06:27
the /stonedb57/install does not contain /bin/ folder is generally a problem with compiling domestic products. What is wrong with your cmake, make and make install?

Or you can add WeChat：StoneDB_2022

**Comment by zsp108** [comment] 2022-08-03 02:49
WeChat communication: Using vmware to deploy, the CPU allocated by the virtual machine is different from the physical machine, and all the instruction sets of the physical machine are not allocated, resulting in an abnormal compilation initialization

you can run ```cat /proc/cpuinfo ``` see cpu info

**Comment by CHENEY-LANCE** [comment] 2022-08-03 02:57
> WeChat communication: Using vmware to deploy, the CPU allocated by the virtual machine is different from the physical machine, and all the instruction sets of the physical machine are not allocated, resulting in an abnormal compilation initialization

So cool！

**Comment by zsp108** [comment] 2022-08-08 02:17
The problem is solved we will close this issue, if not solved you can reopen it

**Closed as completed by zsp108** 2022-08-08 02:17 UTC
Labels: A-bug
