### ISSUE TITLE
bug: ARM platform, union all problem

### ISSUE THREAD

**Issue by davidshiz** [stoneatom/stonedb#1403] opened 2023-03-17 10:30 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/stoneatom/stonedb/blob/stonedb-5.7-dev/CONTRIBUTING.md).

### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the problem

```shell
mysql> SELECT * FROM (SELECT a FROM t1 UNION ALL SELECT a FROM t2) tttt ORDER BY a;
+--------+
| a      |
+--------+
| -32766 |
|     -1 |
|     -1 |
|      0 |
|      0 |
|      1 |
|      1 |
|    127 |
|    130 |
|    255 |
|  32767 |
+--------+
10 rows in set (0.01 sec)
```

### Expected behavior

```shell
mysql> SELECT * FROM (SELECT a FROM t1 UNION ALL SELECT a FROM t2) tttt ORDER BY a;
+--------+
| a      |
+--------+
| -32766 |
|   -126 |
|     -1 |
|     -1 |
|      0 |
|      0 |
|      1 |
|      1 |
|    127 |
|  32767 |
+--------+
10 rows in set (0.01 sec)
```

### How To Reproduce

```sql
CREATE TABLE t1 (a TINYINT);
INSERT INTO t1 VALUES (CAST(0xFFFFFFFFFFFFFF80 AS SIGNED)+2),(-1),(0),(1),(0x7F);
CREATE TABLE t2 (a SMALLINT);
INSERT INTO t2 VALUES (CAST(0xFFFFFFFFFFFF8000 AS SIGNED)+2),(-1),(0),(1),(0x7FFF);
SELECT * FROM (SELECT a FROM t1 UNION ALL SELECT a FROM t2) tttt ORDER BY a;
```

### Environment

```shell
[root@localhost bin]# ./mysqld --version
./mysqld  Ver 5.7.36-StoneDB-v1.0.3 for Linux on aarch64 (build-)
build information as follow: 
        Repository address: https://github.com/stoneatom/stonedb:stonedb-5.7-dev
        Branch name: stonedb-5.7-dev
        Last commit ID: fb58421b3
        Last commit time: Date:   Wed Mar 15 19:32:42 2023 +0800
        Build time: Date: 2023年 03月 16日 星期四 17:59:28 CST
```

### Are you interested in submitting a PR to solve the problem?

- [ ] Yes, I will!

**Comment by wisehead** [comment] 2023-03-21 09:15
the root cause is: on arm the type char is treated as unsigned char by default. we need to add -fsigned-char to the cmake option. problem resolved, will close the issue.

**Closed as completed by wisehead** 2023-03-21 09:15 UTC
Labels: A-bug
